version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: ecogreen_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecogreen
      POSTGRES_PASSWORD: ecogreen
      POSTGRES_DB: ecogreen
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ecogreen_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
